import Anthropic from "@anthropic-ai/sdk";
import { Resend } from "resend";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const resend = new Resend(process.env.RESEND_API_KEY);
const TO_EMAIL = process.env.TO_EMAIL;

const today = new Date().toLocaleDateString("en-GB", {
  day: "numeric",
  month: "long",
  year: "numeric",
});

const SYSTEM_PROMPT = `You are a research assistant for a strategic service designer at a large product company. Your job is to compile a concise, high-signal weekly design digest.

Use the web_search tool to research each of the four topic areas below. For each area, find 2–4 noteworthy items published or discussed in the past 7 days. Prioritise primary sources: articles, announcements, essays, conference talks, and substantive social posts — not summaries of summaries.

Topic areas:
1. Service & strategic design methods — new frameworks, case studies, practice shifts
2. Vibe coding & citizen development — governance thinking, AI-assisted building, enterprise implications
3. Design systems & Figma — updates, new features, community developments
4. What skills service designers need to stay relevant — AI's impact on the profession, emerging role expectations

For each item include:
- A short, plain-English headline
- A 2–3 sentence summary of what happened or what was said
- One sentence on why it matters for a strategic service designer at a large product company

Tone: direct, intellectually honest, no hype, no filler phrases like "it's worth noting" or "exciting developments". If a topic had nothing genuinely interesting this week, say so in one sentence and move on.

Return the digest formatted as a complete HTML email body — clean, readable, no external CSS dependencies. Use inline styles only. Structure:
- A simple header with the title "Design digest" and the date
- Four sections, one per topic area, each with a coloured left border to distinguish them
- Each item as a small card or block with headline, summary, and why-it-matters
- A short footer with the text "Generated by Claude"

The full output should be valid HTML that can be dropped directly into an email body.`;

async function runDigest() {
  console.log(`Running digest for ${today}…`);

  const messages = [
    {
      role: "user",
      content: `Please research and compile the weekly design digest for the week ending ${today}. Search each topic area and return the full HTML digest.`,
    },
  ];

  let htmlDigest = null;

  // Agentic loop — keep processing until the model stops calling tools
  while (true) {
    const response = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 8192,
      system: SYSTEM_PROMPT,
      tools: [
        {
          type: "web_search_20250305",
          name: "web_search",
          max_uses: 20,
        },
      ],
      messages,
    });

    console.log(`Stop reason: ${response.stop_reason}`);

    // Accumulate assistant message
    messages.push({ role: "assistant", content: response.content });

    if (response.stop_reason === "end_turn") {
      // Extract the text block containing the HTML
      const textBlock = response.content.find((b) => b.type === "text");
      if (textBlock) {
        htmlDigest = textBlock.text;
      }
      break;
    }

    if (response.stop_reason === "tool_use") {
      // Process all tool calls and collect results
      const toolResults = [];

      for (const block of response.content) {
        if (block.type === "tool_use") {
          console.log(`  Searching: "${block.input.query}"`);
          // web_search results are returned automatically by the API —
          // we just need to feed back a tool_result placeholder so the
          // conversation continues. The actual search is executed server-side.
          toolResults.push({
            type: "tool_result",
            tool_use_id: block.id,
            content: "", // server-side tool; result is injected by the API
          });
        }
      }

      messages.push({ role: "user", content: toolResults });
      continue;
    }

    // Any other stop reason — bail out
    console.error(`Unexpected stop reason: ${response.stop_reason}`);
    break;
  }

  if (!htmlDigest) {
    throw new Error("No HTML digest was produced by the model.");
  }

  console.log("Digest generated. Sending email…");

  const { data, error } = await resend.emails.send({
    from: "onboarding@resend.dev",
    to: TO_EMAIL,
    subject: `Design digest — ${today}`,
    html: htmlDigest,
  });

  if (error) {
    throw new Error(`Resend error: ${JSON.stringify(error)}`);
  }

  console.log(`Email sent. ID: ${data.id}`);
}

runDigest().catch((err) => {
  console.error(err);
  process.exit(1);
});
