import Anthropic from "@anthropic-ai/sdk";
import { Resend } from "resend";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const resend = new Resend(process.env.RESEND_API_KEY);
const TO_EMAIL = process.env.TO_EMAIL;

const today = new Date().toLocaleDateString("en-GB", {
  day: "numeric",
  month: "long",
  year: "numeric",
});

const RESEARCH_SYSTEM_PROMPT = `You are a research assistant for a strategic service designer at a large product company. Your job is to find high-signal content published in the past 7 days.

Use the web_search tool to research each of the four topic areas below. For each area, find 2–4 noteworthy items. Prioritise primary sources: articles, announcements, essays, conference talks, and substantive social posts — not summaries of summaries.

Topic areas:
1. Service & strategic design methods — new frameworks, case studies, practice shifts
2. Vibe coding & citizen development — governance thinking, AI-assisted building, enterprise implications
3. Design systems & Figma — updates, new features, community developments
4. What skills service designers need to stay relevant — AI's impact on the profession, emerging role expectations

For each topic area return 2–3 bullet points maximum. Each bullet must contain:
- Headline (plain English, one line)
- Summary (2 sentences max)
- Why it matters (1 sentence)
- Source URL

Strict length limit: the entire output across all four topics must be 1500 words or fewer. Cut anything that doesn't add signal. No padding, no preamble, no closing remarks.

Tone: direct, intellectually honest, no hype, no filler phrases like "it's worth noting" or "exciting developments". If a topic had nothing genuinely interesting this week, say so in one sentence and move on.

Return plain structured text only — no HTML. This will be passed to a separate step that handles formatting.`;

const WRITER_SYSTEM_PROMPT = `You are an HTML email formatter. You will receive a structured research summary and must convert it into a complete HTML email body.

Requirements:
- Clean, readable, no external CSS dependencies — inline styles only
- A simple header with the title "Design digest" and the date
- Four sections, one per topic area, each with a coloured left border to distinguish them
- Each item as a small card or block with headline, summary, and why-it-matters
- A short footer with the text "Generated by Claude"

Return only valid HTML that can be dropped directly into an email body. No markdown, no explanation — just the HTML.`;

// Call 1: Research agent — runs the agentic loop with web_search enabled.
// Returns a plain-text research summary; no HTML formatting here.
async function runResearch() {
  console.log("Step 1: Researching topics…");

  const messages = [
    {
      role: "user",
      content: `Please research the weekly design digest topics for the week ending ${today}. Search each of the four topic areas and return your findings as structured plain text.`,
    },
  ];

  while (true) {
    const response = await anthropic.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 8192,
      system: RESEARCH_SYSTEM_PROMPT,
      tools: [
        {
          type: "web_search_20250305",
          name: "web_search",
          max_uses: 20,
        },
      ],
      messages,
    });

    console.log(`  Research stop reason: ${response.stop_reason}`);
    messages.push({ role: "assistant", content: response.content });

    if (response.stop_reason === "end_turn") {
      const textBlock = response.content.find((b) => b.type === "text");
      if (!textBlock) throw new Error("Research call returned no text.");
      return textBlock.text;
    }

    if (response.stop_reason === "tool_use") {
      const toolResults = [];
      for (const block of response.content) {
        if (block.type === "tool_use") {
          console.log(`    Searching: "${block.input.query}"`);
          toolResults.push({
            type: "tool_result",
            tool_use_id: block.id,
            content: "",
          });
        }
      }
      messages.push({ role: "user", content: toolResults });
      continue;
    }

    throw new Error(`Unexpected research stop reason: ${response.stop_reason}`);
  }
}

// Call 2: Writer — single non-agentic call with no tools.
// Receives the full research summary and returns only HTML.
// Gets the entire max_tokens budget for writing.
async function runWriter(researchSummary) {
  console.log("Step 2: Writing HTML digest…");

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 8192,
    system: WRITER_SYSTEM_PROMPT,
    messages: [
      {
        role: "user",
        content: `Here is the research summary for the week ending ${today}. Please format it as the HTML email digest.\n\n${researchSummary}`,
      },
    ],
  });

  const textBlock = response.content.find((b) => b.type === "text");
  if (!textBlock) throw new Error("Writer call returned no text.");
  return textBlock.text;
}

async function runDigest() {
  console.log(`Running digest for ${today}…`);

  const researchSummary = await runResearch();

  console.log("Research summary preview:", researchSummary.slice(0, 500));

  console.log("Waiting 90 seconds before writer call to avoid rate limit…");
  await new Promise((resolve) => setTimeout(resolve, 90000));

  const htmlDigest = await runWriter(researchSummary);

  console.log("Digest generated. Sending email…");

  const { data, error } = await resend.emails.send({
    from: "onboarding@resend.dev",
    to: TO_EMAIL,
    subject: `Design digest — ${today}`,
    html: htmlDigest,
  });

  if (error) {
    throw new Error(`Resend error: ${JSON.stringify(error)}`);
  }

  console.log(`Email sent. ID: ${data.id}`);
}

runDigest().catch((err) => {
  console.error(err);
  process.exit(1);
});
